N_BLOCK - 9
T_CALL
T_IDENTIFIER - srand
T_COMMA - 1
T_NUMBER - 0
T_EQ
T_CALL
T_IDENTIFIER - rand
T_COMMA - 0
T_IDENTIFIER - a
T_CALL
T_IDENTIFIER - print2
T_COMMA - 2
T_IDENTIFIER - a
T_IDENTIFIER - print
T_EQ
T_STRING - "%ld/\%ld"
T_IDENTIFIER - g
T_EQ
T_NUMBER - 1
T_IDENTIFIER - k
T_CALL
T_IDENTIFIER - printf
T_COMMA - 4
T_STRING - "printf: %ld %ld %ld END
"
T_IDENTIFIER - k
T_NUMBER - 2222
T_IDENTIFIER - a
T_CALL
T_IDENTIFIER - printf
T_COMMA - 4
T_STRING - "sizes: %ld %ld %ld
"
T_CALL
T_IDENTIFIER - sizeof
T_COMMA - 0
T_CALL
T_IDENTIFIER - sizeof
T_COMMA - 1
T_NUMBER - 2222
T_CALL
T_IDENTIFIER - sizeof
T_COMMA - 1
T_IDENTIFIER - g
T_AT (81604444213)
T_IDENTIFIER - add
T_COMMA - 2
T_EQ
T_NUMBER - 0
T_IDENTIFIER - b
T_EQ
T_NUMBER - 0
T_IDENTIFIER - c
N_BLOCK - 1
T_RETURN (90194640901)
T_MUL (90195296278)
T_IDENTIFIER - b
T_IDENTIFIER - c
T_AT (98784313397)
T_IDENTIFIER - minus
T_COMMA - 1
T_EQ
T_NUMBER - 0
T_IDENTIFIER - gh
N_BLOCK - 1
T_RETURN (107374510085)
T_NUMBER - 1223
